### PR TITLE
fix: display project image on click only on mobile

### PR DESCRIPTION
**Pull request by izzett222**
## Describe your changes

Display the project image when the user clicks on the project title on mobile and hide the project card when the user hasn't clicked on it.
## Issue ticket number and link
id -> #030
link -> [here](https://www.notion.so/apeunit/project-section-click-effect-on-mobile-f9ddb40f027447a0a5fbd3065ebdc273)

## Tasks completed

- [x] display project image on click only on mobile
- [x] hide the project card when the user hasn't clicked on the project title
## Tasks not completed
None
## Screenshots (if needed)

### CODE REVIEW

**Review by mhenriette — APPROVED** [review]
LGTM!!

**Review by hirwaaldo1 — CHANGES_REQUESTED** [review]
on mobile it does not work it only works when  you click twice, may be you change that

**Review by mutesialine — APPROVED** [review]
well done. it looks good

**Review by mutesialine — APPROVED** [review]

**Review by hirwaaldo1 — APPROVED** [review]
well done

**Pull request merged**
